# Generated by Django 6.0.5 on 2026-05-20 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên sân bóng')),
                ('pitch_type', models.CharField(choices=[('5', 'Sân 5 người'), ('7', 'Sân 7 người'), ('11', 'Sân 11 người')], default='5', max_length=2, verbose_name='Loại sân')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá thuê (VND/Giờ)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả chi tiết')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pitch_images/', verbose_name='Hình ảnh sân')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitches', to=settings.AUTH_USER_MODEL, verbose_name='Chủ sân')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(verbose_name='Ngày đặt')),
                ('start_time', models.TimeField(verbose_name='Giờ bắt đầu')),
                ('end_time', models.TimeField(verbose_name='Giờ kết thúc')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tổng tiền thanh toán')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('canceled', 'Đã hủy')], default='pending', max_length=10, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng')),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='pitches.pitch', verbose_name='Sân bóng')),
            ],
        ),
    ]
