# Generated by Django 6.0.5 on 2026-05-20 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='pitch_type',
            field=models.CharField(choices=[('5', '5 người'), ('7', '7 người'), ('11', '11 người')], default='5', max_length=2, verbose_name='Loại sân'),
        ),
    ]
